[project]
name = "tmm-pytorch"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "setuptools>=80.9.0",
    "torch>=2.8.0",
]
